### ISSUE TITLE
Can you put the Golden Apple beatHit?

### ISSUE THREAD

**Issue by juanroman74454811** [Reycko/FNF_Maevings-Remake#1]
its my fav one

**Comment by Reycko** [comment]
I'll try, but i'm porting the mod to mods/ so I can do custom stuff & updates, but i'll still try it

**Comment by Reycko** [comment]
> > I'll try, but i'm porting the mod to mods/ so I can do custom stuff & updates, but i'll still try it
> 
> pizza tower network jumpscare

WAIT HOLD THE FUCK ON

**Comment by juanroman74454811** [comment]
> > > I'll try, but i'm porting the mod to mods/ so I can do custom stuff & updates, but i'll still try it
> > 
> > 
> > pizza tower network jumpscare
> 
> WAIT HOLD THE FUCK ON

what

**Comment by Reycko** [comment]
> > > > I'll try, but i'm porting the mod to mods/ so I can do custom stuff & updates, but i'll still try it
> > > 
> > > 
> > > pizza tower network jumpscare
> > 
> > 
> > WAIT HOLD THE FUCK ON
> 
> what

do you still play PTN

**Comment by juanroman74454811** [comment]
> > > > > I'll try, but i'm porting the mod to mods/ so I can do custom stuff & updates, but i'll still try it
> > > > 
> > > > 
> > > > pizza tower network jumpscare
> > > 
> > > 
> > > WAIT HOLD THE FUCK ON
> > 
> > 
> > what
> 
> do you still play PTN

PTN:E moment
