### ISSUE TITLE
add tax fraud

### ISSUE THREAD

**Issue by raf13lol** [Reycko/FNF_Maevings-Remake#4]
# Is your feature request related to a problem? Please describe.
## A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
I WANT SEX...

# Describe the solution you'd like
## A clear and concise description of what you want to happen.
add tax fraud

# Describe alternatives you've considered
## A clear and concise description of any alternative solutions or features you've considered.
paying legally (boring)

# Additional context
## Add any other context or screenshots about the feature request here.
ok thanks

**Comment by Reycko** [comment]
Uhm... No!

**Comment by raf13lol** [comment]
i disagree.

**Comment by Reycko** [comment]
> i disagree.

Then suck my dick.

**Comment by raf13lol** [comment]
oh thanks for adding tax fraud
